---
apiVersion: v2
name: oem-hi-app
description: oem-hi-app
home: https://github.com/catenax-ng/product-behaviour-twin-libraries
type: application
appVersion: "0.0.1"
version: 0.0.1
maintainers: []

dependencies:
  - name: postgresql
    version: "15.0"
    repository: https://charts.bitnami.com/bitnami
